project:
  type: website

website:
  title: LLM AI Gameplay Analysis
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO-523-SU24/final-project # Need to change to your project repo
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: Write Up
        href: write_up.qmd  
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto
